aws-cost-reporter:
  branches:
    - main
  container: true
  container_url: "https://quay.io/repository/redhat_msi/aws-cost-reporter"
  github_url: https://github.com/RedHatQE/aws-cost-reporter
  release: true
  release_url: ""

ci-jobs-trigger:
  branches:
    - main
  container: true
  container_url: https://quay.io/repository/redhat_msi/ci-jobs-trigger
  github_url: https://github.com/RedHatQE/ci-jobs-trigger
  release: true
  release_url: https://github.com/RedHatQE/ci-jobs-trigger/releases

cloud-tools:
  branches:
    - main
  container: false
  container_url: ""
  github_url: https://github.com/RedHatQE/cloud-tools
  release: true
  release_url: https://pypi.org/project/redhat-qe-cloud-tools/

fedora-zsh:
  branches:
    - main
  container: false
  container_url: ""
  github_url: https://github.com/RedHatQE/fedora-zsh
  release: false
  release_url: ""

firewatch:
  branches:
    - main
  container: false
  container_url: ""
  github_url: https://github.com/RedHatQE/firewatch
  release: false
  release_url: ""

flake8-plugins:
  branches:
    - main
  container: false
  container_url: ""
  github_url: https://github.com/RedHatQE/flake8-plugins
  release: false
  release_url: ""

github-webhook-server:
  branches:
    - main
  container: true
  container_url: "https://quay.io/repository/myakove/github-webhook-server"
  github_url: https://github.com/myk-org/github-webhook-server
  release: true
  release_url: https://pypi.org/project/github-webhook-server/

hive-claim-manager:
  branches:
    - main
  container: true
  container_url: https://github.com/RedHatQE/hive-claim-manager
  github_url: https://github.com/RedHatQE/hive-claim-manager
  release: true
  release_url: ""

ocp-addons-operators-cli:
  branches:
    - main
  container: true
  container_url: https://quay.io/repository/redhat_msi/ocp-addons-operators-cli
  github_url: https://github.com/RedHatQE/ocp-addons-operators-cli
  release: true
  release_url: https://github.com/RedHatQE/ocp-addons-operators-cli/releases

openshift-cli-installer:
  branches:
    - main
  container: true
  container_url: https://quay.io/repository/redhat_msi/openshift-cli-installer
  github_url: https://github.com/RedHatQE/openshift-cli-installer
  release: true
  release_url: https://pypi.org/project/openshift-cli-installer/

openshift-cluster-management-python-client:
  branches:
    - main
  container: false
  container_url: ""
  github_url: https://github.com/RedHatQE/openshift-cluster-management-python-client
  release: true
  release_url: <[openshift-cluster-management-python-client](https://pypi.org/project/openshift-cluster-management-python-client/)>

openshift-cluster-management-python-wrapper:
  branches:
    - main
  container: false
  container_url: ""
  github_url: https://github.com/RedHatQE/openshift-cluster-management-python-wrapper
  release: true
  release_url: https://pypi.org/project/openshift-cluster-management-python-wrapper/

openshift-day2-configurator:
  branches:
    - main
  container: false
  container_url: ""
  github_url: https://github.com/RedHatQE/openshift-day2-configurator
  release: true
  release_url: https://pypi.org/project/openshift-day2-configurator/

openshift-python-utilities:
  branches:
    - main
  container: false
  container_url: ""
  github_url: https://github.com/RedHatQE/openshift-python-utilities
  release: true
  release_url: https://pypi.org/project/openshift-python-utilities/

openshift-python-wrapper:
  branches:
    - main
    - v4.18
    - v4.17
    - v4.16
  container: false
  container_url: ""
  github_url: https://github.com/RedHatQE/openshift-python-wrapper
  release: true
  release_url: https://pypi.org/project/openshift-python-wrapper/

openshift-python-wrapper-data-collector:
  branches:
    - main
  container: false
  container_url: ""
  github_url: https://github.com/RedHatQE/openshift-python-wrapper-data-collector
  release: true
  release_url: https://pypi.org/project/openshift-python-wrapper-data-collector/

pyhelper-utils:
  branches:
    - main
  container: false
  container_url: ""
  github_url: https://github.com/RedHatQE/pyhelper-utils
  release: true
  release_url: https://pypi.org/project/pyhelper-utils/

python-simple-logger:
  branches:
    - main
  container: false
  container_url: ""
  github_url: https://github.com/RedHatQE/python-simple-logger
  release: true
  release_url: https://pypi.org/project/python-simple-logger/

python-utility-scripts:
  branches:
    - main
  container: false
  container_url: ""
  github_url: https://github.com/RedHatQE/python-utility-scripts
  release: true
  release_url: https://pypi.org/project/python-utility-scripts/

qe-metrics:
  branches:
    - main
  container: true
  container_url: " quay.io/redhatqe/qe-metrics"
  github_url: https://github.com/RedHatQE/qe-metrics
  release: true
  release_url: "https://github.com/RedHatQE/qe-metrics/releases"

qe-tools-base-image:
  branches:
    - main
  container: true
  container_url: https://quay.io/repository/redhat_msi/qe-tools-base-image
  github_url: https://github.com/RedHatQE/qe-tools-base-image
  release: true
  release_url: ""

rosa-python-client:
  branches:
    - main
  container: false
  container_url: ""
  github_url: https://github.com/RedHatQE/rosa-python-client
  release: true
  release_url: https://pypi.org/project/rosa-python-client/

timeout-sampler:
  branches:
    - main
  container: false
  container_url: ""
  github_url: https://github.com/RedHatQE/timeout-sampler
  release: true
  release_url: https://pypi.org/project/timeout-sampler/

vaultrun:
  branches:
    - main
  container: false
  container_url: ""
  github_url: https://github.com/RedHatQE/vaultrun
  release: true
  release_url: https://pypi.org/project/vaultrun/

mtv-api-tests:
  branches:
    - main
  container: true
  container_url: TBD
  github_url: https://github.com/RedHatQE/mtv-api-tests
  release: false
